# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  database: dev_venok
  host: db
  username: postgres
  password:
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: prod_rails4
